export const listData1 = [
  {
    id: 1,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 14,
    date: '10:30, 22 Sep',
    priority: 'tinggi',
    status: 'Read',
  },
  {
    id: 2,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 2,
    date: '09:00, 23 Sep',
    priority: 'rendah',
    status: 'Sekretaris',
  },
  {
    id: 3,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 14,
    date: '15:45, 24 Sep',
    priority: 'rendah',
    status: 'Disposisi',
  },
  {
    id: 4,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 14,
    date: '10:30, 22 Sep',
    priority: 'tinggi',
    status: 'Disposisi',
  },
  {
    id: 5,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 2,
    date: '09:00, 23 Sep',
    priority: 'tinggi',
    status: 'Unread',
  },
  {
    id: 6,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 14,
    date: '15:45, 24 Sep',
    priority: 'sedang',
    status: 'Read',
  },
  {
    id: 7,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 14,
    date: '10:30, 22 Sep',
    priority: 'sedang',
    status: 'Read',
  },
  {
    id: 8,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 2,
    date: '09:00, 23 Sep',
    priority: 'sedang',
    status: 'Unread',
  },
  {
    id: 9,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 14,
    date: '15:45, 24 Sep',
    priority: 'tinggi',
    status: 'Read',
  },
];
export const listData2 = [
  {
    id: 10,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 14,
    date: '10:30, 22 Sep',
    priority: 'rendah',
    status: 'Sekretaris',
  },
  {
    id: 11,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 2,
    date: '09:00, 23 Sep',
    priority: 'rendah',
    status: 'Sekretaris',
  },
  {
    id: 12,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 14,
    date: '15:45, 24 Sep',
    priority: 'sedang',
    status: 'Disposisi',
  },
  {
    id: 13,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 14,
    date: '10:30, 22 Sep',
    priority: 'sedang',
    status: 'Disposisi',
  },
  {
    id: 14,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 2,
    date: '09:00, 23 Sep',
    priority: 'tinggi',
    status: 'Unread',
  },
  {
    id: 15,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 14,
    date: '15:45, 24 Sep',
    priority: 'tinggi',
    status: 'Read',
  },
];
export const listData3 = [
  {
    id: 15,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 14,
    date: '10:30, 22 Sep',
    priority: 'tinggi',
    status: 'Read',
  },
  {
    id: 16,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 2,
    date: '09:00, 23 Sep',
    priority: 'rendah',
    status: 'Unread',
  },
  {
    id: 17,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 14,
    date: '15:45, 24 Sep',
    priority: 'sedang',
    status: 'Unread',
  },
];
