import avatarRed from '../../../../assets/SuratKeluar/AvatarRed.svg';
export const listData1 = [
  {
    id: 1,
    avatarSrc: avatarRed,
    primary: 'Komisaris',
    secondary:
      'Undangan Workshop Pemahaman ISO90012015 Layanan Contact  Center',
    messageCount: 0,
    date: '10:30, 22 Sep',
    priority: 'Normal',
    status: 'Read',
    noAgenda: 'In.02/HK',
    tanggalKirim: '26-07-2021',
    noSurat: 'In.02/HK',
    dari: 'Jabatan Pegawai',
    kepada: 'Direktur Utama',
    tembusan: 'Direktur Utama',
    perihal: 'Undangan Workshop',
    lampiran: 3,
    jenis: 'Biasa',
    nama: 'John Smith',
    nik: '11908876',
    kodeDepart: 'JB07',
    departemen: 'Departemen A',
    kotaKantor: 'Bandung',
    pemeriksa: 'Pemeriksa A',
    pemohon: 'Pemohon A',
  },
  {
    id: 2,
    avatarSrc: avatarRed,
    primary: 'Komisaris',
    secondary:
      'Undangan Workshop Pemahaman ISO90012015 Layanan Contact  Center',
    messageCount: 0,
    date: '09:00, 23 Sep',
    priority: 'Normal',
    status: 'Sekretaris',
    noAgenda: 'In.02/HK',
    tanggalKirim: '26-07-2021',
    noSurat: 'In.02/HK',
    dari: 'Jabatan Pegawai',
    kepada: 'Direktur Utama',
    tembusan: 'Direktur Utama',
    perihal: 'Undangan Workshop',
    lampiran: 3,
    jenis: 'Biasa',
    nama: 'John Smith',
    nik: '11908876',
    kodeDepart: 'JB07',
    departemen: 'Departemen A',
    kotaKantor: 'Bandung',
    pemeriksa: 'Pemeriksa A',
    pemohon: 'Pemohon A',
  },
  {
    id: 3,
    avatarSrc: avatarRed,
    primary: 'Komisaris',
    secondary:
      'Undangan Workshop Pemahaman ISO90012015 Layanan Contact  Center',
    messageCount: 0,
    date: '15:45, 24 Sep',
    priority: 'Normal',
    status: 'Disposisi',
    noAgenda: 'In.02/HK',
    tanggalKirim: '26-07-2021',
    noSurat: 'In.02/HK',
    dari: 'Jabatan Pegawai',
    kepada: 'Direktur Utama',
    tembusan: 'Direktur Utama',
    perihal: 'Undangan Workshop',
    lampiran: 3,
    jenis: 'Biasa',
    nama: 'John Smith',
    nik: '11908876',
    kodeDepart: 'JB07',
    departemen: 'Departemen A',
    kotaKantor: 'Bandung',
    pemeriksa: 'Pemeriksa A',
    pemohon: 'Pemohon A',
  },
  {
    id: 4,
    avatarSrc: avatarRed,
    primary: 'Komisaris',
    secondary:
      'Undangan Workshop Pemahaman ISO90012015 Layanan Contact  Center',
    messageCount: 0,
    date: '10:30, 22 Sep',
    priority: 'Normal',
    status: 'Disposisi',
    noAgenda: 'In.02/HK',
    tanggalKirim: '26-07-2021',
    noSurat: 'In.02/HK',
    dari: 'Jabatan Pegawai',
    kepada: 'Direktur Utama',
    tembusan: 'Direktur Utama',
    perihal: 'Undangan Workshop',
    lampiran: 3,
    jenis: 'Biasa',
    nama: 'John Smith',
    nik: '11908876',
    kodeDepart: 'JB07',
    departemen: 'Departemen A',
    kotaKantor: 'Bandung',
    pemeriksa: 'Pemeriksa A',
    pemohon: 'Pemohon A',
  },
  {
    id: 5,
    avatarSrc: avatarRed,
    primary: 'Komisaris',
    secondary:
      'Undangan Workshop Pemahaman ISO90012015 Layanan Contact  Center',
    messageCount: 0,
    date: '09:00, 23 Sep',
    priority: 'Normal',
    status: 'Unread',
    noAgenda: 'In.02/HK',
    tanggalKirim: '26-07-2021',
    noSurat: 'In.02/HK',
    dari: 'Jabatan Pegawai',
    kepada: 'Direktur Utama',
    tembusan: 'Direktur Utama',
    perihal: 'Undangan Workshop',
    lampiran: 3,
    jenis: 'Biasa',
    nama: 'John Smith',
    nik: '11908876',
    kodeDepart: 'JB07',
    departemen: 'Departemen A',
    kotaKantor: 'Bandung',
    pemeriksa: 'Pemeriksa A',
    pemohon: 'Pemohon A',
  },
  {
    id: 6,
    avatarSrc: avatarRed,
    primary: 'Komisaris',
    secondary:
      'Undangan Workshop Pemahaman ISO90012015 Layanan Contact  Center',
    messageCount: 0,
    date: '15:45, 24 Sep',
    priority: 'Normal',
    status: 'Read',
    noAgenda: 'In.02/HK',
    tanggalKirim: '26-07-2021',
    noSurat: 'In.02/HK',
    dari: 'Jabatan Pegawai',
    kepada: 'Direktur Utama',
    tembusan: 'Direktur Utama',
    perihal: 'Undangan Workshop',
    lampiran: 3,
    jenis: 'Biasa',
    nama: 'John Smith',
    nik: '11908876',
    kodeDepart: 'JB07',
    departemen: 'Departemen A',
    kotaKantor: 'Bandung',
    pemeriksa: 'Pemeriksa A',
    pemohon: 'Pemohon A',
  },
  {
    id: 7,
    avatarSrc: avatarRed,
    primary: 'Komisaris',
    secondary:
      'Undangan Workshop Pemahaman ISO90012015 Layanan Contact  Center',
    messageCount: 0,
    date: '10:30, 22 Sep',
    priority: 'Normal',
    status: 'Read',
    noAgenda: 'In.02/HK',
    tanggalKirim: '26-07-2021',
    noSurat: 'In.02/HK',
    dari: 'Jabatan Pegawai',
    kepada: 'Direktur Utama',
    tembusan: 'Direktur Utama',
    perihal: 'Undangan Workshop',
    lampiran: 3,
    jenis: 'Biasa',
    nama: 'John Smith',
    nik: '11908876',
    kodeDepart: 'JB07',
    departemen: 'Departemen A',
    kotaKantor: 'Bandung',
    pemeriksa: 'Pemeriksa A',
    pemohon: 'Pemohon A',
  },
  {
    id: 8,
    avatarSrc: avatarRed,
    primary: 'Komisaris',
    secondary:
      'Undangan Workshop Pemahaman ISO90012015 Layanan Contact  Center',
    messageCount: 0,
    date: '09:00, 23 Sep',
    priority: 'Normal',
    status: 'Unread',
    noAgenda: 'In.02/HK',
    tanggalKirim: '26-07-2021',
    noSurat: 'In.02/HK',
    dari: 'Jabatan Pegawai',
    kepada: 'Direktur Utama',
    tembusan: 'Direktur Utama',
    perihal: 'Undangan Workshop',
    lampiran: 3,
    jenis: 'Biasa',
    nama: 'John Smith',
    nik: '11908876',
    kodeDepart: 'JB07',
    departemen: 'Departemen A',
    kotaKantor: 'Bandung',
    pemeriksa: 'Pemeriksa A',
    pemohon: 'Pemohon A',
  },
  {
    id: 9,
    avatarSrc: avatarRed,
    primary: 'Komisaris',
    secondary:
      'Undangan Workshop Pemahaman ISO90012015 Layanan Contact  Center',
    messageCount: 0,
    date: '15:45, 24 Sep',
    priority: 'Normal',
    status: 'Read',
    noAgenda: 'In.02/HK',
    tanggalKirim: '26-07-2021',
    noSurat: 'In.02/HK',
    dari: 'Jabatan Pegawai',
    kepada: 'Direktur Utama',
    tembusan: 'Direktur Utama',
    perihal: 'Undangan Workshop',
    lampiran: 3,
    jenis: 'Biasa',
    nama: 'John Smith',
    nik: '11908876',
    kodeDepart: 'JB07',
    departemen: 'Departemen A',
    kotaKantor: 'Bandung',
    pemeriksa: 'Pemeriksa A',
    pemohon: 'Pemohon A',
  },
];
export const listData2 = [
  {
    id: 1,
    avatarSrc: avatarRed,
    primary: 'Komisaris',
    secondary:
      'Undangan Workshop Pemahaman ISO90012015 Layanan Contact  Center',
    messageCount: 0,
    date: '10:30, 22 Sep',
    priority: 'Normal',
    status: 'Read',
    noAgenda: 'In.02/HK',
    tanggalKirim: '26-07-2021',
    noSurat: 'In.02/HK',
    dari: 'Jabatan Pegawai',
    kepada: 'Direktur Utama',
    tembusan: 'Direktur Utama',
    perihal: 'Undangan Workshop',
    lampiran: 3,
    jenis: 'Biasa',
    nama: 'John Smith',
    nik: '11908876',
    kodeDepart: 'JB07',
    departemen: 'Departemen A',
    kotaKantor: 'Bandung',
    pemeriksa: 'Pemeriksa A',
    pemohon: 'Pemohon A',
  },
  {
    id: 2,
    avatarSrc: avatarRed,
    primary: 'Komisaris',
    secondary:
      'Undangan Workshop Pemahaman ISO90012015 Layanan Contact  Center',
    messageCount: 0,
    date: '09:00, 23 Sep',
    priority: 'Normal',
    status: 'Sekretaris',
    noAgenda: 'In.02/HK',
    tanggalKirim: '26-07-2021',
    noSurat: 'In.02/HK',
    dari: 'Jabatan Pegawai',
    kepada: 'Direktur Utama',
    tembusan: 'Direktur Utama',
    perihal: 'Undangan Workshop',
    lampiran: 3,
    jenis: 'Biasa',
    nama: 'John Smith',
    nik: '11908876',
    kodeDepart: 'JB07',
    departemen: 'Departemen A',
    kotaKantor: 'Bandung',
    pemeriksa: 'Pemeriksa A',
    pemohon: 'Pemohon A',
  },
  {
    id: 3,
    avatarSrc: avatarRed,
    primary: 'Komisaris',
    secondary:
      'Undangan Workshop Pemahaman ISO90012015 Layanan Contact  Center',
    messageCount: 0,
    date: '15:45, 24 Sep',
    priority: 'Normal',
    status: 'Disposisi',
    noAgenda: 'In.02/HK',
    tanggalKirim: '26-07-2021',
    noSurat: 'In.02/HK',
    dari: 'Jabatan Pegawai',
    kepada: 'Direktur Utama',
    tembusan: 'Direktur Utama',
    perihal: 'Undangan Workshop',
    lampiran: 3,
    jenis: 'Biasa',
    nama: 'John Smith',
    nik: '11908876',
    kodeDepart: 'JB07',
    departemen: 'Departemen A',
    kotaKantor: 'Bandung',
    pemeriksa: 'Pemeriksa A',
    pemohon: 'Pemohon A',
  },
  {
    id: 4,
    avatarSrc: avatarRed,
    primary: 'Komisaris',
    secondary:
      'Undangan Workshop Pemahaman ISO90012015 Layanan Contact  Center',
    messageCount: 0,
    date: '10:30, 22 Sep',
    priority: 'Normal',
    status: 'Disposisi',
    noAgenda: 'In.02/HK',
    tanggalKirim: '26-07-2021',
    noSurat: 'In.02/HK',
    dari: 'Jabatan Pegawai',
    kepada: 'Direktur Utama',
    tembusan: 'Direktur Utama',
    perihal: 'Undangan Workshop',
    lampiran: 3,
    jenis: 'Biasa',
    nama: 'John Smith',
    nik: '11908876',
    kodeDepart: 'JB07',
    departemen: 'Departemen A',
    kotaKantor: 'Bandung',
    pemeriksa: 'Pemeriksa A',
    pemohon: 'Pemohon A',
  },
  {
    id: 5,
    avatarSrc: avatarRed,
    primary: 'Komisaris',
    secondary:
      'Undangan Workshop Pemahaman ISO90012015 Layanan Contact  Center',
    messageCount: 0,
    date: '09:00, 23 Sep',
    priority: 'Normal',
    status: 'Unread',
    noAgenda: 'In.02/HK',
    tanggalKirim: '26-07-2021',
    noSurat: 'In.02/HK',
    dari: 'Jabatan Pegawai',
    kepada: 'Direktur Utama',
    tembusan: 'Direktur Utama',
    perihal: 'Undangan Workshop',
    lampiran: 3,
    jenis: 'Biasa',
    nama: 'John Smith',
    nik: '11908876',
    kodeDepart: 'JB07',
    departemen: 'Departemen A',
    kotaKantor: 'Bandung',
    pemeriksa: 'Pemeriksa A',
    pemohon: 'Pemohon A',
  },
  {
    id: 6,
    avatarSrc: avatarRed,
    primary: 'Komisaris',
    secondary:
      'Undangan Workshop Pemahaman ISO90012015 Layanan Contact  Center',
    messageCount: 0,
    date: '15:45, 24 Sep',
    priority: 'Normal',
    status: 'Read',
    noAgenda: 'In.02/HK',
    tanggalKirim: '26-07-2021',
    noSurat: 'In.02/HK',
    dari: 'Jabatan Pegawai',
    kepada: 'Direktur Utama',
    tembusan: 'Direktur Utama',
    perihal: 'Undangan Workshop',
    lampiran: 3,
    jenis: 'Biasa',
    nama: 'John Smith',
    nik: '11908876',
    kodeDepart: 'JB07',
    departemen: 'Departemen A',
    kotaKantor: 'Bandung',
    pemeriksa: 'Pemeriksa A',
    pemohon: 'Pemohon A',
  },
  {
    id: 7,
    avatarSrc: avatarRed,
    primary: 'Komisaris',
    secondary:
      'Undangan Workshop Pemahaman ISO90012015 Layanan Contact  Center',
    messageCount: 0,
    date: '10:30, 22 Sep',
    priority: 'Normal',
    status: 'Read',
    noAgenda: 'In.02/HK',
    tanggalKirim: '26-07-2021',
    noSurat: 'In.02/HK',
    dari: 'Jabatan Pegawai',
    kepada: 'Direktur Utama',
    tembusan: 'Direktur Utama',
    perihal: 'Undangan Workshop',
    lampiran: 3,
    jenis: 'Biasa',
    nama: 'John Smith',
    nik: '11908876',
    kodeDepart: 'JB07',
    departemen: 'Departemen A',
    kotaKantor: 'Bandung',
    pemeriksa: 'Pemeriksa A',
    pemohon: 'Pemohon A',
  },
  {
    id: 8,
    avatarSrc: avatarRed,
    primary: 'Komisaris',
    secondary:
      'Undangan Workshop Pemahaman ISO90012015 Layanan Contact  Center',
    messageCount: 0,
    date: '09:00, 23 Sep',
    priority: 'Normal',
    status: 'Unread',
    noAgenda: 'In.02/HK',
    tanggalKirim: '26-07-2021',
    noSurat: 'In.02/HK',
    dari: 'Jabatan Pegawai',
    kepada: 'Direktur Utama',
    tembusan: 'Direktur Utama',
    perihal: 'Undangan Workshop',
    lampiran: 3,
    jenis: 'Biasa',
    nama: 'John Smith',
    nik: '11908876',
    kodeDepart: 'JB07',
    departemen: 'Departemen A',
    kotaKantor: 'Bandung',
    pemeriksa: 'Pemeriksa A',
    pemohon: 'Pemohon A',
  },
  {
    id: 9,
    avatarSrc: avatarRed,
    primary: 'Komisaris',
    secondary:
      'Undangan Workshop Pemahaman ISO90012015 Layanan Contact  Center',
    messageCount: 0,
    date: '15:45, 24 Sep',
    priority: 'Normal',
    status: 'Read',
    noAgenda: 'In.02/HK',
    tanggalKirim: '26-07-2021',
    noSurat: 'In.02/HK',
    dari: 'Jabatan Pegawai',
    kepada: 'Direktur Utama',
    tembusan: 'Direktur Utama',
    perihal: 'Undangan Workshop',
    lampiran: 3,
    jenis: 'Biasa',
    nama: 'John Smith',
    nik: '11908876',
    kodeDepart: 'JB07',
    departemen: 'Departemen A',
    kotaKantor: 'Bandung',
    pemeriksa: 'Pemeriksa A',
    pemohon: 'Pemohon A',
  },
];
export const listData3 = [
  {
    id: 1,
    avatarSrc: avatarRed,
    primary: 'Komisaris',
    secondary:
      'Undangan Workshop Pemahaman ISO90012015 Layanan Contact  Center',
    messageCount: 0,
    date: '10:30, 22 Sep',
    priority: 'Normal',
    status: 'Read',
    noAgenda: 'In.02/HK',
    tanggalKirim: '26-07-2021',
    noSurat: 'In.02/HK',
    dari: 'Jabatan Pegawai',
    kepada: 'Direktur Utama',
    tembusan: 'Direktur Utama',
    perihal: 'Undangan Workshop',
    lampiran: 3,
    jenis: 'Biasa',
    nama: 'John Smith',
    nik: '11908876',
    kodeDepart: 'JB07',
    departemen: 'Departemen A',
    kotaKantor: 'Bandung',
    pemeriksa: 'Pemeriksa A',
    pemohon: 'Pemohon A',
  },
  {
    id: 2,
    avatarSrc: avatarRed,
    primary: 'Komisaris',
    secondary:
      'Undangan Workshop Pemahaman ISO90012015 Layanan Contact  Center',
    messageCount: 0,
    date: '09:00, 23 Sep',
    priority: 'Normal',
    status: 'Sekretaris',
    noAgenda: 'In.02/HK',
    tanggalKirim: '26-07-2021',
    noSurat: 'In.02/HK',
    dari: 'Jabatan Pegawai',
    kepada: 'Direktur Utama',
    tembusan: 'Direktur Utama',
    perihal: 'Undangan Workshop',
    lampiran: 3,
    jenis: 'Biasa',
    nama: 'John Smith',
    nik: '11908876',
    kodeDepart: 'JB07',
    departemen: 'Departemen A',
    kotaKantor: 'Bandung',
    pemeriksa: 'Pemeriksa A',
    pemohon: 'Pemohon A',
  },
  {
    id: 3,
    avatarSrc: avatarRed,
    primary: 'Komisaris',
    secondary:
      'Undangan Workshop Pemahaman ISO90012015 Layanan Contact  Center',
    messageCount: 0,
    date: '15:45, 24 Sep',
    priority: 'Normal',
    status: 'Disposisi',
    noAgenda: 'In.02/HK',
    tanggalKirim: '26-07-2021',
    noSurat: 'In.02/HK',
    dari: 'Jabatan Pegawai',
    kepada: 'Direktur Utama',
    tembusan: 'Direktur Utama',
    perihal: 'Undangan Workshop',
    lampiran: 3,
    jenis: 'Biasa',
    nama: 'John Smith',
    nik: '11908876',
    kodeDepart: 'JB07',
    departemen: 'Departemen A',
    kotaKantor: 'Bandung',
    pemeriksa: 'Pemeriksa A',
    pemohon: 'Pemohon A',
  },
  {
    id: 4,
    avatarSrc: avatarRed,
    primary: 'Komisaris',
    secondary:
      'Undangan Workshop Pemahaman ISO90012015 Layanan Contact  Center',
    messageCount: 0,
    date: '10:30, 22 Sep',
    priority: 'Normal',
    status: 'Disposisi',
    noAgenda: 'In.02/HK',
    tanggalKirim: '26-07-2021',
    noSurat: 'In.02/HK',
    dari: 'Jabatan Pegawai',
    kepada: 'Direktur Utama',
    tembusan: 'Direktur Utama',
    perihal: 'Undangan Workshop',
    lampiran: 3,
    jenis: 'Biasa',
    nama: 'John Smith',
    nik: '11908876',
    kodeDepart: 'JB07',
    departemen: 'Departemen A',
    kotaKantor: 'Bandung',
    pemeriksa: 'Pemeriksa A',
    pemohon: 'Pemohon A',
  },
  {
    id: 5,
    avatarSrc: avatarRed,
    primary: 'Komisaris',
    secondary:
      'Undangan Workshop Pemahaman ISO90012015 Layanan Contact  Center',
    messageCount: 0,
    date: '09:00, 23 Sep',
    priority: 'Normal',
    status: 'Unread',
    noAgenda: 'In.02/HK',
    tanggalKirim: '26-07-2021',
    noSurat: 'In.02/HK',
    dari: 'Jabatan Pegawai',
    kepada: 'Direktur Utama',
    tembusan: 'Direktur Utama',
    perihal: 'Undangan Workshop',
    lampiran: 3,
    jenis: 'Biasa',
    nama: 'John Smith',
    nik: '11908876',
    kodeDepart: 'JB07',
    departemen: 'Departemen A',
    kotaKantor: 'Bandung',
    pemeriksa: 'Pemeriksa A',
    pemohon: 'Pemohon A',
  },
  {
    id: 6,
    avatarSrc: avatarRed,
    primary: 'Komisaris',
    secondary:
      'Undangan Workshop Pemahaman ISO90012015 Layanan Contact  Center',
    messageCount: 0,
    date: '15:45, 24 Sep',
    priority: 'Normal',
    status: 'Read',
    noAgenda: 'In.02/HK',
    tanggalKirim: '26-07-2021',
    noSurat: 'In.02/HK',
    dari: 'Jabatan Pegawai',
    kepada: 'Direktur Utama',
    tembusan: 'Direktur Utama',
    perihal: 'Undangan Workshop',
    lampiran: 3,
    jenis: 'Biasa',
    nama: 'John Smith',
    nik: '11908876',
    kodeDepart: 'JB07',
    departemen: 'Departemen A',
    kotaKantor: 'Bandung',
    pemeriksa: 'Pemeriksa A',
    pemohon: 'Pemohon A',
  },
  {
    id: 7,
    avatarSrc: avatarRed,
    primary: 'Komisaris',
    secondary:
      'Undangan Workshop Pemahaman ISO90012015 Layanan Contact  Center',
    messageCount: 0,
    date: '10:30, 22 Sep',
    priority: 'Normal',
    status: 'Read',
    noAgenda: 'In.02/HK',
    tanggalKirim: '26-07-2021',
    noSurat: 'In.02/HK',
    dari: 'Jabatan Pegawai',
    kepada: 'Direktur Utama',
    tembusan: 'Direktur Utama',
    perihal: 'Undangan Workshop',
    lampiran: 3,
    jenis: 'Biasa',
    nama: 'John Smith',
    nik: '11908876',
    kodeDepart: 'JB07',
    departemen: 'Departemen A',
    kotaKantor: 'Bandung',
    pemeriksa: 'Pemeriksa A',
    pemohon: 'Pemohon A',
  },
  {
    id: 8,
    avatarSrc: avatarRed,
    primary: 'Komisaris',
    secondary:
      'Undangan Workshop Pemahaman ISO90012015 Layanan Contact  Center',
    messageCount: 0,
    date: '09:00, 23 Sep',
    priority: 'Normal',
    status: 'Unread',
    noAgenda: 'In.02/HK',
    tanggalKirim: '26-07-2021',
    noSurat: 'In.02/HK',
    dari: 'Jabatan Pegawai',
    kepada: 'Direktur Utama',
    tembusan: 'Direktur Utama',
    perihal: 'Undangan Workshop',
    lampiran: 3,
    jenis: 'Biasa',
    nama: 'John Smith',
    nik: '11908876',
    kodeDepart: 'JB07',
    departemen: 'Departemen A',
    kotaKantor: 'Bandung',
    pemeriksa: 'Pemeriksa A',
    pemohon: 'Pemohon A',
  },
  {
    id: 9,
    avatarSrc: avatarRed,
    primary: 'Komisaris',
    secondary:
      'Undangan Workshop Pemahaman ISO90012015 Layanan Contact  Center',
    messageCount: 0,
    date: '15:45, 24 Sep',
    priority: 'Normal',
    status: 'Read',
    noAgenda: 'In.02/HK',
    tanggalKirim: '26-07-2021',
    noSurat: 'In.02/HK',
    dari: 'Jabatan Pegawai',
    kepada: 'Direktur Utama',
    tembusan: 'Direktur Utama',
    perihal: 'Undangan Workshop',
    lampiran: 3,
    jenis: 'Biasa',
    nama: 'John Smith',
    nik: '11908876',
    kodeDepart: 'JB07',
    departemen: 'Departemen A',
    kotaKantor: 'Bandung',
    pemeriksa: 'Pemeriksa A',
    pemohon: 'Pemohon A',
  },
];
