import user from '../../../../assets/vector/Avatar.png';
export const users = [
  {
    profil: user,
    id: 1,
    nama: 'John Doe',
    alamat: 'Jalan Merdeka No. 123',
    nikg: '1234567890',
    nikl: '0987654321',
    kota: 'Jakarta',
    organisasi: 'Perusahaan ABC',
    divisi: 'IT',
    departemen: 'Teknologi Informasi',
    kode_departemen: 'TI-001',
    jabatan: 'Programmer',
    email: 'john.doe@example.com',
    pgs: 'ini pgs yagesya',
    nohp: '081234567890',
    personal: true,
  },
  {
    profil: user,
    id: 2,
    nama: 'Jane Smith',
    alamat: 'Jalan Mawar No. 456',
    nikg: '0987654321',
    nikl: '1234567890',
    kota: 'Surabaya',
    organisasi: 'Perusahaan XYZ',
    divisi: 'IT',
    departemen: 'Akuntansi',
    kode_departemen: 'AK-001',
    jabatan: 'Akuntan',
    email: 'jane.smith@example.com',
    pgs: 'ini pgs yagesya',
    nohp: '087654321098',
    personal: false,
  },
  {
    profil: user,
    id: 3,
    nama: 'Ahmad Ibrahim',
    alamat: 'Jalan Raya No. 789',
    nikg: '1357924680',
    nikl: '2468013579',
    kota: 'Bandung',
    organisasi: 'Perusahaan ABC',
    divisi: 'IT',
    departemen: 'SDM',
    kode_departemen: 'SDM-001',
    jabatan: 'HRD Manager',
    email: 'ahmad.ibrahim@example.com',
    pgs: 'ini pgs yagesya',
    nohp: '081357924680',
    personal: true,
  },
  {
    profil: user,
    id: 4,
    nama: 'Maria Gonzalez',
    alamat: '123 Main Street',
    nikg: '9876543210',
    nikl: '0123456789',
    kota: 'Bali',
    organisasi: 'Perusahaan XYZ',
    divisi: 'Pemasaran',
    departemen: 'Marketing',
    kode_departemen: 'MK-001',
    jabatan: 'Marketing Manager',
    email: 'maria.gonzalez@example.com',
    pgs: 'ini pgs yagesya',
    nohp: '089876543210',
    personal: true,
  },
  {
    profil: user,
    id: 5,
    nama: 'Chen Wei',
    alamat: '123 Elm Street',
    nikg: '5432167890',
    nikl: '6789054321',
    kota: 'Shanghai',
    organisasi: 'Perusahaan ABC',
    divisi: 'Keuangan',
    departemen: 'Sales',
    kode_departemen: 'S-001',
    jabatan: 'Sales Executive',
    email: 'chen.wei@example.com',
    pgs: 'ini pgs yagesya',
    nohp: '086789054321',
    personal: true,
  },
  {
    profil: user,
    id: 6,
    nama: 'Anna Kowalski',
    alamat: '456 Oak Street',
    nikg: '6789054321',
    nikl: '5432167890',
    kota: 'Warsaw',
    organisasi: 'Perusahaan XYZ',
    divisi: 'Keuangan',
    departemen: 'Manufaktur',
    kode_departemen: 'M-001',
    jabatan: 'Production Manager',
    email: 'anna.kowalski@example.com',
    pgs: 'ini pgs yagesya',
    nohp: '087890543216',
    personal: false,
  },
  {
    profil: user,
    id: 7,
    nama: 'Muhammad Al-Mansur',
    alamat: '789 Pine Street',
    nikg: '4567890123',
    nikl: '5678901234',
    kota: 'Cairo',
    organisasi: 'Perusahaan ABC',
    divisi: 'Keuangan',
    departemen: 'Logistik',
    kode_departemen: 'LG-001',
    jabatan: 'Logistics Coordinator',
    email: 'muhammad.almansur@example.com',
    pgs: 'ini pgs yagesya',
    nohp: '085678901234',
    personal: false,
  },
  {
    profil: user,
    id: 8,
    nama: 'Sophie Dubois',
    alamat: '987 Maple Street',
    nikg: '3210987654',
    nikl: '4321098765',
    kota: 'Paris',
    organisasi: 'Perusahaan XYZ',
    divisi: 'Keuangan',
    departemen: 'R&D',
    kode_departemen: 'RND-001',
    jabatan: 'Research Scientist',
    email: 'sophie.dubois@example.com',
    pgs: 'ini pgs yagesya',
    nohp: '083210987654',
    personal: false,
  },
  {
    profil: user,
    id: 9,
    nama: 'David Johnson',
    alamat: '321 Birch Street',
    nikg: '2345678901',
    nikl: '3456789012',
    kota: 'New York',
    organisasi: 'Perusahaan ABC',
    divisi: 'IT',
    departemen: 'CEO Office',
    kode_departemen: 'CEO-001',
    jabatan: 'CEO',
    email: 'david.johnson@example.com',
    pgs: 'ini pgs yagesya',
    nohp: '082345678901',
    personal: false,
  },
  {
    profil: user,
    id: 10,
    nama: 'John Doe',
    alamat: 'Jalan Merdeka No. 123',
    nikg: '1234567890',
    nikl: '0987654321',
    kota: 'Jakarta',
    organisasi: 'Perusahaan ABC',
    divisi: 'IT',
    departemen: 'Teknologi Informasi',
    kode_departemen: 'TI-001',
    jabatan: 'Programmer',
    email: 'john.doe@example.com',
    pgs: 'ini pgs yagesya',
    nohp: '081234567890',
    personal: true,
  },
  {
    profil: user,
    id: 11,
    nama: 'John Doe',
    alamat: 'Jalan Merdeka No. 123',
    nikg: '1234567890',
    nikl: '0987654321',
    kota: 'Jakarta',
    organisasi: 'Perusahaan ABC',
    divisi: 'IT',
    departemen: 'Teknologi Informasi',
    kode_departemen: 'TI-001',
    jabatan: 'Programmer',
    email: 'john.doe@example.com',
    pgs: 'ini pgs yagesya',
    nohp: '081234567890',
    personal: true,
  },
  {
    profil: user,
    id: 12,
    nama: 'John Doe',
    alamat: 'Jalan Merdeka No. 123',
    nikg: '1234567890',
    nikl: '0987654321',
    kota: 'Jakarta',
    organisasi: 'Perusahaan ABC',
    divisi: 'IT',
    departemen: 'Teknologi Informasi',
    kode_departemen: 'TI-001',
    jabatan: 'Programmer',
    email: 'john.doe@example.com',
    pgs: 'ini pgs yagesya',
    nohp: '081234567890',
    personal: true,
  },
  {
    profil: user,
    id: 13,
    nama: 'Muhammad Al-Mansur',
    alamat: '789 Pine Street',
    nikg: '4567890123',
    nikl: '5678901234',
    kota: 'Cairo',
    organisasi: 'Perusahaan ABC',
    divisi: 'IT',
    departemen: 'Logistik',
    kode_departemen: 'LG-001',
    jabatan: 'Logistics Coordinator',
    email: 'muhammad.almansur@example.com',
    pgs: 'ini pgs yagesya',
    nohp: '085678901234',
    personal: true,
  },
];
